version: "3.2"
services:
  traced-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DD_ENV=prod
      - DD_AGENT_HOST=dd-agent
    ports:
      - "8080:80"

  dd-agent:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOG_LEVEL=error
    image: 'datadog/agent'
